### ISSUE TITLE
Docker installtion Fails

### ISSUE THREAD

**Issue by ilovefreesw** [websu-io/websu#1]
![image](https://user-images.githubusercontent.com/77317006/105573979-6025f300-5d87-11eb-80d8-cc505a33765c.png)

Web UI and API don't work. Gives 404.

**Comment by samos123** [comment]
Thank you for raising this issue. The API does work in your situation, you can try it by by running the following:
```
curl -d '{"url": "https://www.google.com"}' localhost:8000/reports
```
or by going to http://localhost/reports in a browser.

The Web UI however is indeed broken and I've fixed it just now in commit c08c310. Can you try again by running the following?
```
docker-compose stop
docker-compose pull
docker-compose up -d
```
Let me know if that works and if you have any other issues or feedback. Thank you for trying Websu out. Feel free to re-open if it still doesn't work for you.

**Comment by ilovefreesw** [comment]
![image](https://user-images.githubusercontent.com/77317006/105662529-f37d3680-5ef5-11eb-96ef-25dad44d8941.png)

Works now. Thanks.

**Comment by samos123** [comment]
Woohoo. Thanks for confirming it's working now
