### ISSUE TITLE
Changing UI

### ISSUE THREAD

**Issue by shockmousemedia** [websu-io/websu#2]
Love this repo. Wondering how I would go about editing the UI for my own uses?

**Comment by samos123** [comment]
Thanks for the feedback. You have 2 options:
1. Fork the React based websu-ui repo: https://github.com/websu-io/websu-ui
2. Create your own UI by using the websu-API

Honestly I am not that great at building UI so my focus has been on API/backend piece of it. I started websu mostly as a side project to learn golang and Google Cloud Run.
