### ISSUE TITLE
( Solved )error run-tests.sh

### ISSUE THREAD

**Issue by jarac794** [websu-io/websu#21]
I'm not that expert, but I'll report the sh you have to update lighthouse 7.2 has bad routes https://github.com/websu-io/websu/pkg/lighthouse is one of the routes but I think everyone is missing a route / tree

**Comment by samos123** [comment]
unclear what the issue is. `./run-tests.sh unit` is working fine for me.  Can you post your full output of `./run-tests.sh unit`?

**Comment by jarac794** [comment]
hello no sorry close it I had not made the change from localhost to ip
