### ISSUE TITLE
I can't Unsubscribe email from websu. 

### ISSUE THREAD

**Issue by haodmp** [websu-io/websu#24]
I try websu. But now it too spam. I don't wanna received email but it still send me

**Comment by samos123** [comment]
What's the URL you used? I can remove it for you.

**Comment by samos123** [comment]
I might just turn it off for all for now

**Comment by haodmp** [comment]
My website need unsubcribe:
charmenuochoa.com
vuhuyphuong.com

Can you update function for user unsub easy jn future

Thạn you,
Best regard

Vào 14:50, Th 3, 20 thg 12, 2022 Sam Stoelinga ***@***.***>
đã viết:

**Comment by samos123** [comment]
I have stopped all recurring report generation for all URLs for now since I didn't have time to build unsubscribe yet. Apologies for that. Life got in the way and haven't had as much time for Websu.
